k2:
  metadata:
    id: k2.blocks.structures.config.branch-env-config
    kind: "template"
  body:
    name: "branch-env-config"
    parameters:
      name: "branch-env-config"
      description: "Per-Branch JSON config file"
      partition: k2-blocks
      system: structures
      version: "0.0.1"
      isProd: false