k2:
  metadata:
    id: "<%= namespace %>.config"
    kind: template-apply
  body:
    template:
      source: git
      params:
        repository: https://github.com/tuxounet/k2-blocks-structures.git
        branch: dev
        path: "config/branch-env-config/k2.template.yaml"
    vars:
      name: "config"
      description: "Config folder"
